name: WAV
favicon: null
layout_spectrum: 0.88693
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#76C25D'
    - '#B2D4A5'
    - '#82AE6F'
    - '#CCE7C0'
  brandStrength: 0.504223
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
