name: WAV
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Green Wave Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#76c25d'
    - '#b2d4a5'
    - '#82ae6f'
    - '#cce7c0'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
