analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#6eff28'
    - '#002364'
    - '#2e4d82'
    - '#a9bad8'
  brandStrength: 0.6875
  lightness: 0.5625
  rhythmicContrast: 0
  saturation: 0.5625
cta: {}
layout_spectrum: 1
name: WAV
opengraph: {}
purpose: []
typography_spectrum: 1
