analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#76C25D'
    - '#B2D4A5'
    - '#82AE6F'
    - '#CCE7C0'
  brandStrength: 0.504223
  lightness: 0.625
  rhythmicContrast: 0
  saturation: 0.5625
cta: {}
layout_spectrum: 1
name: WAV
opengraph: {}
purpose: []
typography_spectrum: 1
