name: WAV
favicon: null
layout_spectrum: 0.87747
typography_spectrum: 0.76324
title: Green Wave Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#76C25D'
    - '#B2D4A5'
    - '#82AE6F'
    - '#CCE7C0'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
