name: WAV
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Green Wave Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6eff28'
    - '#002364'
    - '#2e4d82'
    - '#a9bad8'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
