analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#76c25d'
    - '#b2d4a5'
    - '#82ae6f'
    - '#cce7c0'
  brandStrength: 0.765203
  lightness: 0.625
  rhythmicContrast: 0
  saturation: 0.5625
cta: {}
layout_spectrum: 1
name: WAV
opengraph: {}
purpose: []
typography_spectrum: 1
